module.exports = (client) => {
    
    // ... (any existing canvas code you have can stay up here) ...

    client.on('messageCreate', async (message) => {
        // 1. Ignore bots
        if (message.author.bot) return;

        // 2. Listen for the .imagine prefix
        if (message.content.toLowerCase().startsWith('.imagine ')) {
            // Cut out the ".imagine " part to get exactly what the user wants to draw
            const prompt = message.content.slice(9).trim();
            
            if (!prompt) {
                return message.reply('Please tell me what to draw! Example: `.imagine a futuristic city at sunset`');
            }

            // 3. Send a temporary message so the user knows the bot isn't frozen
            const replyMsg = await message.reply('🎨 Painting your picture... give me a few seconds!');

            try {
                // 4. Format the prompt safely for a URL
                const safePrompt = encodeURIComponent(prompt);
                
                // Pollinations.ai generates the image instantly via a URL link
                // We request a 1024x1024 image without the watermark
                const imageUrl = `https://image.pollinations.ai/prompt/${safePrompt}?width=1024&height=1024&nologo=true`;

                // 5. Send the final image back to Discord
                await message.channel.send({
                    content: `🖼️ **${prompt}**\nGenerated by ${message.author}`,
                    files: [imageUrl] // Discord will automatically download and attach the image!
                });

                // Delete the temporary "Painting..." message to keep chat clean
                await replyMsg.delete();

            } catch (error) {
                console.error("Image Gen Error:", error.message);
                await replyMsg.edit('❌ Sorry, I had trouble drawing that. Please try a different prompt!');
            }
        }
    });
};
