services:
  - type: web
    name: starry-bot
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
