const { Groq } = require('groq-sdk');
const { PermissionFlagsBits } = require('discord.js');

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

const aiCooldowns = new Set();

const moderationTools = [
    {
        type: "function",
        function: {
            name: "clear_messages",
            description: "Deletes a specific number of messages from the channel.",
            parameters: {
                type: "object",
                properties: {
                    amount: { type: "number", description: "The number of messages to clear (1-100)." }
                },
                required: ["amount"]
            }
        }
    },
    {
        type: "function",
        function: {
            name: "kick_member",
            description: "Kicks a member from the server.",
            parameters: {
                type: "object",
                properties: {
                    userId: { type: "string", description: "The mention or ID of the user to kick." },
                    reason: { type: "string", description: "The reason for the kick." }
                },
                required: ["userId"]
            }
        }
    },
    {
        type: "function",
        function: {
            name: "ban_member",
            description: "Bans a member from the server.",
            parameters: {
                type: "object",
                properties: {
                    userId: { type: "string", description: "The mention or ID of the user to ban." },
                    reason: { type: "string", description: "The reason for the ban." }
                },
                required: ["userId"]
            }
        }
    }
];

module.exports = (client) => {
    client.on('messageCreate', async (message) => {
        // 1. Ignore bots and empty messages
        if (message.author.bot || !message.content) return;

        const text = message.content.toLowerCase();

        // ==========================================
        // IMAGE GENERATOR (.imagine)
        // ==========================================
        if (text.startsWith('.imagine ')) {
            const imagePrompt = message.content.slice(9).trim();
            if (!imagePrompt) return message.reply('Please tell me what to draw!').catch(()=>{});

            // Safety net: Stops crashing if Discord blocks the bot in this channel
            const replyMsg = await message.reply('🎨 Painting your picture...').catch(() => null);
            if (!replyMsg) return; 

            try {
                const safePrompt = encodeURIComponent(imagePrompt);
                const imageUrl = `https://image.pollinations.ai/prompt/${safePrompt}?width=1024&height=1024&nologo=true`;
                
                await message.reply({ content: `🖼️ **${imagePrompt}**\nGenerated by ${message.author}`, files: [imageUrl] }).catch(() => {});
                return await replyMsg.delete().catch(() => {});
            } catch (error) {
                return replyMsg.edit('❌ Trouble drawing that.').catch(() => {});
            }
        }

        // ==========================================
        // TEXT & MODERATION CONVERSATION
        // ==========================================
        
        // SMART TRIGGERS: Check if someone is actually talking to Starry
        const mentionsBot = message.mentions.has(client.user.id);
        const containsName = text.includes('starry');
        
        let isReplyToBot = false;
        if (message.reference) {
            try {
                const repliedMessage = await message.channel.messages.fetch(message.reference.messageId);
                if (repliedMessage.author.id === client.user.id) isReplyToBot = true;
            } catch (err) {}
        }

        // If no one said "Starry", pinged her, or replied to her... stay quiet!
        if (!mentionsBot && !containsName && !isReplyToBot) return;

        // Cooldowns
        if (aiCooldowns.has(message.author.id)) return;
        aiCooldowns.add(message.author.id);
        setTimeout(() => aiCooldowns.delete(message.author.id), 4000);

        // Send typing indicator safely
        await message.channel.sendTyping().catch(() => {});

        try {
            const chatCompletion = await groq.chat.completions.create({
                messages: [
                    { 
                        role: "system", 
                        content: "You are Starry, a helpful and friendly Discord bot. Talk naturally and conversationally like a human. DO NOT use JSON, tags, or code in your regular replies. ONLY use your moderation tools if the user explicitly asks you to kick, ban, or clear messages." 
                    },
                    { role: "user", content: `${message.author.username} says: ${message.content}` }
                ],
                model: "llama-3.1-8b-instant",
                tools: moderationTools,
                tool_choice: "auto"
            });

            const responseMessage = chatCompletion.choices[0].message;

            let functionName = null;
            let args = null;

            if (responseMessage.tool_calls && responseMessage.tool_calls.length > 0) {
                const toolCall = responseMessage.tool_calls[0];
                functionName = toolCall.function.name;
                args = JSON.parse(toolCall.function.arguments);
            }
            else if (responseMessage.content && responseMessage.content.includes('(function=')) {
                const match = responseMessage.content.match(/\(function=([^>]+)>(.*?)\)<\/function>/is);
                if (match) {
                    functionName = match[1];
                    try {
                        args = JSON.parse(match[2]);
                    } catch (e) {}
                }
            }

            if (functionName && args) {
                if (!message.member.permissions.has(PermissionFlagsBits.ManageMessages) && functionName === 'clear_messages') {
                    return message.reply(`❌ Sorry, you don't have permission to clear messages!`).catch(()=>{});
                }
                if (!message.member.permissions.has(PermissionFlagsBits.KickMembers) && functionName === 'kick_member') {
                    return message.reply(`❌ Sorry, you don't have permission to kick members!`).catch(()=>{});
                }
                if (!message.member.permissions.has(PermissionFlagsBits.BanMembers) && functionName === 'ban_member') {
                    return message.reply(`❌ Sorry, you don't have permission to ban members!`).catch(()=>{});
                }

                if (functionName === "clear_messages") {
                    const amount = Math.min(args.amount || 0, 100);
                    if (amount <= 0) return message.reply("❌ Please specify a valid number of messages to clear.").catch(()=>{});
                    
                    await message.channel.bulkDelete(amount + 1, true).catch(()=>{});
                    
                    const modLog = await message.channel.send(`🧹 Cleared ${amount} messages!`).catch(()=>{});
                    if (modLog) {
                        setTimeout(() => modLog.delete().catch(() => {}), 4000);
                    }
                    return;
                }

                const rawId = args.userId || "";
                const targetId = String(rawId).replace(/\D/g, ''); 
                
                if (!targetId || targetId.length < 15) {
                    return message.reply("❌ Please actually `@mention` the user so I can grab their correct Discord ID!").catch(()=>{});
                }

                const targetMember = await message.guild.members.fetch(targetId).catch(() => null);

                if (!targetMember) return message.reply("❌ I couldn't find that member. Did they already leave, or was the ping invalid?").catch(()=>{});
                if (!targetMember.modifiable) return message.reply("❌ I cannot moderate this user. Their role is higher than mine!").catch(()=>{});

                if (functionName === "kick_member") {
                    try {
                        await targetMember.kick(args.reason || "Kicked by Starry AI");
                        return message.reply(`✅ Successfully kicked **${targetMember.user.tag}**.`);
                    } catch (err) {
                        return message.reply("❌ Discord blocked the kick! Check my permissions.").catch(()=>{});
                    }
                }

                if (functionName === "ban_member") {
                    try {
                        await targetMember.ban({ reason: args.reason || "Banned by Starry AI" });
                        return message.reply(`✅ Successfully banned **${targetMember.user.tag}**.`);
                    } catch (err) {
                        return message.reply("❌ Discord blocked the ban! Check my permissions.").catch(()=>{});
                    }
                }
            }

            let replyText = responseMessage.content || "";

            // Clean up hallucinated tags
            if (replyText.includes('(function=')) {
                replyText = replyText.replace(/\(function=[^>]+\>.*?\<\/function\>/is, '').trim();
            }
            replyText = replyText.replace(/<[a-zA-Z0-9_]+=\{.*?\}>/g, '').trim();

            if (replyText.length > 0) {
                return message.reply(replyText.length > 2000 ? replyText.slice(0, 1995) + "..." : replyText).catch(()=>{});
            }

        } catch (error) {
            console.error("Groq Error:", error.message);
            return message.reply("❌ An internal error occurred while trying to process that command.").catch(()=>{});
        }
    });
};
        
