const { PermissionFlagsBits } = require('discord.js');
const { Groq } = require('groq-sdk');

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

const aiCooldowns = new Set();

module.exports = (client) => {
    client.on('messageCreate', async (message) => {
        // Ignore other bots or empty messages
        if (message.author.bot || !message.content) return;

        const text = message.content.toLowerCase();

        // ==========================================
        // 1. IMAGE GENERATOR (.imagine)
        // ==========================================
        if (text.startsWith('.imagine ')) {
            const imagePrompt = message.content.slice(9).trim();
            if (!imagePrompt) return message.reply('Please tell me what to draw!').catch(() => {});

            const replyMsg = await message.reply('🎨 Painting your picture...').catch(() => null);
            if (!replyMsg) return; 

            try {
                const safePrompt = encodeURIComponent(imagePrompt);
                const imageUrl = `https://image.pollinations.ai/prompt/${safePrompt}?width=1024&height=1024&nologo=true`;

                const cleanFileName = imagePrompt.replace(/\s+/g, '_') + '.png';

                await message.reply({ 
                    content: `🖼️ **${imagePrompt}**\nGenerated by ${message.author}`, 
                    files: [{ attachment: imageUrl, name: cleanFileName }] 
                }).catch(() => {});

                return await replyMsg.delete().catch(() => {});
            } catch (error) {
                console.error("Image Gen Error:", error);
                return replyMsg.edit('❌ Trouble drawing that.').catch(() => {});
            }
        }

        // ==========================================
        // 2. TEXT CONVERSATION & CUSTOM MODERATION
        // ==========================================
        const mentionsBot = message.mentions.has(client.user.id);
        const containsName = text.includes('starry');

        let isReplyToBot = false;
        if (message.reference) {
            try {
                const repliedMessage = await message.channel.messages.fetch(message.reference.messageId);
                if (repliedMessage.author.id === client.user.id) isReplyToBot = true;
            } catch (err) {}
        }

        // Only respond if the bot is mentioned, named, or replied to directly
        if (!mentionsBot && !containsName && !isReplyToBot) return;

        // Anti-spam cooldown
        if (aiCooldowns.has(message.author.id)) return;
        aiCooldowns.add(message.author.id);
        setTimeout(() => aiCooldowns.delete(message.author.id), 4000);

        await message.channel.sendTyping().catch(() => {});

        try {
            const chatCompletion = await groq.chat.completions.create({
                messages: [
                    { 
                        role: "system", 
                        content: `You are Starry, a helpful, playful Discord bot. 
                        
                        RULE 1 (Core Moderation): For kick, ban, unban, clear, timeout, or untimeout, output EXACTLY:
                        [CMD:KICK|ID:123456789012345678|REASON:spam]
                        [CMD:BAN|ID:123456789012345678|REASON:rules]
                        [CMD:UNBAN|ID:123456789012345678]
                        [CMD:CLEAR|AMOUNT:10]
                        [CMD:TIMEOUT|ID:123456789012345678|MINUTES:1|REASON:spam]
                        [CMD:UNTIMEOUT|ID:123456789012345678]
                        Always extract the raw numerical Discord ID from their mention.

                        RULE 2 (Server Commands): If the user asks for real server actions, you MUST output a RUN block.
                        Specific Cheat Sheet:
                        - Giveaways: [RUN:.giveaway 10m Discord Nitro] (You MUST replace 10m and Discord Nitro with the exact time and prize the user asked for)
                        - Lock Channel: [RUN:.lock]
                        - Unlock Channel: [RUN:.unlock]
                        - Truth or Dare: [RUN:.truth] or [RUN:.dare]
                        - Play Music: [RUN:.play despacito]
                        
                        RULE 3 (Casual Chat & Roleplay): If the user asks you a general question, says hello, or asks you to do something imaginary/fun (like cooking noodles, making coffee, or giving a hug), DO NOT use CMD or RUN blocks. Just reply naturally in text and play along enthusiastically!
                        Example: "Starry can you make noodles?" -> "Sure, I'll make it right away! 🍜"` 
                    },
                    { role: "user", content: `${message.author.username} says: ${message.content}` }
                ],
                model: "llama-3.1-8b-instant"
            });

            let replyText = chatCompletion.choices[0].message.content || "";
            let functionName = null;
            let args = {};

            // ==========================================
            // UNIVERSAL COMMAND EXECUTOR (Handles RUN blocks)
            // ==========================================
            const runMatch = replyText.match(/\[.*?RUN:(.*?)\]/i);
            if (runMatch) {
                const simulatedCommand = runMatch[1].trim(); 
                console.log(`🤖 AI attempted to execute: ${simulatedCommand}`); 
                replyText = replyText.replace(runMatch[0], '').trim();

                // Emits the command back to the bot as if the user typed it
                message.content = simulatedCommand;
                client.emit('messageCreate', message);

                if (replyText.length === 0) return;
            }

            // ==========================================
            // NATIVE MODERATION EXECUTOR (Handles CMD blocks)
            // ==========================================
            const cmdMatch = replyText.match(/\[.*?CMD:(KICK|BAN|UNBAN|CLEAR|TIMEOUT|UNTIMEOUT)\|(.*?)\]/i);

            if (cmdMatch) {
                const action = cmdMatch[1].toUpperCase();
                const params = cmdMatch[2].split('|');

                if (action === 'CLEAR') {
                    functionName = 'clear_messages';
                    const amtMatch = params[0].match(/AMOUNT:(\d+)/i);
                    args.amount = amtMatch ? parseInt(amtMatch[1]) : 0;
                } else if (action === 'TIMEOUT') {
                    functionName = 'timeout_member';
                    const idMatch = params.find(p => p.toUpperCase().startsWith('ID:'));
                    const minMatch = params.find(p => p.toUpperCase().startsWith('MINUTES:'));
                    const reasonMatch = params.find(p => p.toUpperCase().startsWith('REASON:'));
                    args.userId = idMatch ? idMatch.substring(3).trim() : "";
                    args.minutes = minMatch ? parseInt(minMatch.substring(8).trim()) : 1;
                    args.reason = reasonMatch ? reasonMatch.substring(7).trim() : "Moderated by Starry AI";
                } else if (action === 'UNTIMEOUT') {
                    functionName = 'untimeout_member';
                    const idMatch = params.find(p => p.toUpperCase().startsWith('ID:'));
                    args.userId = idMatch ? idMatch.substring(3).trim() : "";
                } else if (action === 'UNBAN') {
                    functionName = 'unban_member';
                    const idMatch = params.find(p => p.toUpperCase().startsWith('ID:'));
                    args.userId = idMatch ? idMatch.substring(3).trim() : "";
                } else if (action === 'KICK' || action === 'BAN') {
                    functionName = action === 'KICK' ? 'kick_member' : 'ban_member';
                    const idMatch = params.find(p => p.toUpperCase().startsWith('ID:'));
                    const reasonMatch = params.find(p => p.toUpperCase().startsWith('REASON:'));
                    args.userId = idMatch ? idMatch.substring(3).trim() : "";
                    args.reason = reasonMatch ? reasonMatch.substring(7).trim() : "Moderated by Starry AI";
                }

                replyText = replyText.replace(cmdMatch[0], '').trim();
            }

            // ==========================================
            // MODERATION PERMISSION CHECKS & EXECUTION
            // ==========================================
            if (functionName) {
                if (!message.member.permissions.has(PermissionFlagsBits.ManageMessages) && functionName === 'clear_messages') {
                    return message.reply(`❌ Sorry, you don't have permission to clear messages!`).catch(()=>{});
                }
                if (!message.member.permissions.has(PermissionFlagsBits.KickMembers) && functionName === 'kick_member') {
                    return message.reply(`❌ Sorry, you don't have permission to kick members!`).catch(()=>{});
                }
                if (!message.member.permissions.has(PermissionFlagsBits.BanMembers) && (functionName === 'ban_member' || functionName === 'unban_member')) {
                    return message.reply(`❌ Sorry, you don't have permission to manage bans!`).catch(()=>{});
                }
                if (!message.member.permissions.has(PermissionFlagsBits.ModerateMembers) && (functionName === 'timeout_member' || functionName === 'untimeout_member')) {
                    return message.reply(`❌ Sorry, you don't have permission to manage timeouts!`).catch(()=>{});
                }

                if (functionName === "clear_messages") {
                    const amount = Math.min(args.amount || 0, 100);
                    if (amount <= 0) return message.reply("❌ Please specify a valid number of messages to clear.").catch(()=>{});

                    await message.channel.bulkDelete(amount + 1, true).catch(()=>{});

                    const modLog = await message.channel.send(`🧹 Cleared ${amount} messages!`).catch(()=>{});
                    if (modLog) {
                        setTimeout(() => modLog.delete().catch(() => {}), 4000);
                    }
                    return;
                }

                const rawId = args.userId || "";
                const targetId = String(rawId).replace(/\D/g, ''); 

                if (!targetId || targetId.length < 15) {
                    return message.reply("❌ Please provide a valid Discord ID!").catch(()=>{});
                }

                if (functionName === "unban_member") {
                    try {
                        await message.guild.members.unban(targetId);
                        return message.reply(`✅ Successfully unbanned the user with ID **${targetId}**.`).catch(()=>{});
                    } catch (err) {
                        return message.reply("❌ Discord blocked the unban! Are you sure they are actually banned?").catch(()=>{});
                    }
                }

                const targetMember = await message.guild.members.fetch(targetId).catch(() => null);

                if (!targetMember) return message.reply("❌ I couldn't find that member in the server. Did they already leave, or was the ping invalid?").catch(()=>{});
                if (!targetMember.manageable) return message.reply("❌ I cannot moderate this user. Their role is higher than mine!").catch(()=>{});

                if (functionName === "timeout_member") {
                    try {
                        const durationMs = (args.minutes || 1) * 60 * 1000;
                        await targetMember.timeout(durationMs, args.reason);
                        return message.reply(`✅ Successfully timed out **${targetMember.user.tag}** for ${args.minutes} minute(s).`).catch(()=>{});
                    } catch (err) {
                        return message.reply("❌ Discord blocked the timeout! Check my permissions.").catch(()=>{});
                    }
                }

                if (functionName === "untimeout_member") {
                    try {
                        await targetMember.timeout(null, "Timeout removed by Starry AI");
                        return message.reply(`✅ Successfully removed the timeout for **${targetMember.user.tag}**.`).catch(()=>{});
                    } catch (err) {
                        return message.reply("❌ Discord blocked the action! Check my permissions.").catch(()=>{});
                    }
                }

                if (functionName === "kick_member") {
                    try {
                        await targetMember.kick(args.reason);
                        return message.reply(`✅ Successfully kicked **${targetMember.user.tag}**.`).catch(()=>{});
                    } catch (err) {
                        return message.reply("❌ Discord blocked the kick! Check my permissions.").catch(()=>{});
                    }
                }

                if (functionName === "ban_member") {
                    try {
                        await targetMember.ban({ reason: args.reason });
                        return message.reply(`✅ Successfully banned **${targetMember.user.tag}**.`).catch(()=>{});
                    } catch (err) {
                        return message.reply("❌ Discord blocked the ban! Check my permissions.").catch(()=>{});
                    }
                }
            }

            // Output any standard conversation text generated by the AI
            if (replyText.length > 0) {
                return message.reply(replyText.length > 2000 ? replyText.slice(0, 1995) + "..." : replyText).catch(()=>{});
            }

        } catch (error) {
            console.error("Groq Error:", error.message);
            return message.reply("❌ An internal error occurred while trying to process that command.").catch(()=>{});
        }
    });
};
