const { Groq } = require('groq-sdk');

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

const aiCooldowns = new Set();

module.exports = (client) => {
    client.on('messageCreate', async (message) => {
        // 1. Ignore other bots and empty messages
        if (message.author.bot || !message.content) return;

        const text = message.content.toLowerCase();

        // ==========================================
        // FEATURE 1: THE .IMAGINE IMAGE GENERATOR
        // ==========================================
        if (text.startsWith('.imagine ')) {
            const imagePrompt = message.content.slice(9).trim();
            
            if (!imagePrompt) {
                return message.reply('Please tell me what to draw! Example: `.imagine a futuristic city`');
            }

            const replyMsg = await message.reply('🎨 Painting your picture... give me a few seconds!');

            try {
                const safePrompt = encodeURIComponent(imagePrompt);
                const imageUrl = `https://image.pollinations.ai/prompt/${safePrompt}?width=1024&height=1024&nologo=true`;

                await message.channel.send({
                    content: `🖼️ **${imagePrompt}**\nGenerated by ${message.author}`,
                    files: [imageUrl]
                });

                return await replyMsg.delete();
            } catch (error) {
                console.error("Image Gen Error:", error.message);
                return replyMsg.edit('❌ Sorry, I had trouble drawing that.');
            }
        }

        // ==========================================
        // FEATURE 2: NORMAL TEXT CONVERSATION
        // ==========================================
        const mentionsBot = message.mentions.has(client.user.id);
        const containsName = text.includes('starry');
        
        // Check if replying directly to the bot
        let isReplyToBot = false;
        if (message.reference) {
            try {
                const repliedMessage = await message.channel.messages.fetch(message.reference.messageId);
                if (repliedMessage.author.id === client.user.id) {
                    isReplyToBot = true;
                }
            } catch (err) {
                // Ignore reply fetch errors safely
            }
        }

        // If they aren't talking to the bot, ignore the message
        if (!mentionsBot && !containsName && !isReplyToBot) return;
            
        // Check Cooldown for chatting
        if (aiCooldowns.has(message.author.id)) {
            return message.reply('⏳ Give me a second to process that!');
        }

        // Clean the prompt for the AI
        let prompt = message.content.replace(`<@${client.user.id}>`, '');
        prompt = prompt.replace(/starry/ig, '').trim();
        
        if (!prompt) {
            return message.reply("Hey there! Did you need me?");
        }

        // Apply 5-second chat cooldown
        aiCooldowns.add(message.author.id);
        setTimeout(() => aiCooldowns.delete(message.author.id), 5000);

        await message.channel.sendTyping();

        try {
            const chatCompletion = await groq.chat.completions.create({
                messages: [
                    { role: "system", content: "You are Starry, a helpful, friendly, and concise Discord bot. Talk like a normal person in a chat room." },
                    { role: "user", content: prompt }
                ],
                model: "llama-3.1-8b-instant", 
            });

            const replyText = chatCompletion.choices[0]?.message?.content || "I'm drawing a blank right now.";

            if (replyText.length > 2000) {
                return message.reply(replyText.slice(0, 1995) + "...");
            }

            return message.reply(replyText);

        } catch (error) {
            console.error("Groq AI Error:", error.message);
            return message.reply('❌ I am having trouble connecting to my AI brain right now.');
        }
    });
};
              
