// ==========================================
// 🧪 UNIT TESTS: STARRY AUTONOMOUS BOT STUDIO
// File Path: tests/botStudio.test.js
// ==========================================
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const child_process = require('child_process');
const botStudio = require('../src/modules/botStudio');

console.log('🧪 Starting Starry Autonomous Bot Studio Test Suite...\n');

// 1. Test Bot Creation Intent Detection
console.log('▶ Test 1: Bot Creation Intent Detection');
// The exact prompt from the user's screenshot:
assert.strictEqual(botStudio.isBotCreationRequest('--dev code code a complex discord bot for me'), true);
assert.strictEqual(botStudio.isBotCreationRequest('code a complex discord bot for me'), true);
assert.strictEqual(botStudio.isBotCreationRequest('make a discord bot for me'), true);
assert.strictEqual(botStudio.isBotCreationRequest('build me a music bot'), true);
assert.strictEqual(botStudio.isBotCreationRequest('create a moderation bot'), true);
assert.strictEqual(botStudio.isBotCreationRequest(',codebot advanced economy bot'), true);
assert.strictEqual(botStudio.isBotCreationRequest('/codebot'), true);

// Negative checks (regular questions should NOT trigger bot studio)
assert.strictEqual(botStudio.isBotCreationRequest('Why is the sky blue?'), false);
assert.strictEqual(botStudio.isBotCreationRequest('Explain quantum physics'), false);
assert.strictEqual(botStudio.isBotCreationRequest('Write a python function to sort an array'), false);
console.log('  ✅ Intent detection tests passed with 100% accuracy!');

// 2. Test Session Creation & Choice Payload
console.log('\n▶ Test 2: Session Creation & Choice Payload');
const testUser = { id: '1234567890', username: 'TestWizard' };
const session = botStudio.createBotStudioSession(testUser.id, '--dev code code a complex discord bot for me');
assert.ok(session.id, 'Session should have unique ID');
assert.strictEqual(session.userId, testUser.id);
assert.ok(botStudio.botStudioSessions.has(session.id), 'Session must be cached');

const payload = botStudio.buildBotStudioChoicePayload(session);
assert.ok(payload.embeds && payload.embeds.length === 1, 'Should have 1 embed');
assert.ok(payload.components && payload.components.length === 1, 'Should have 1 action row');
const buttons = payload.components[0].components;
assert.strictEqual(buttons.length, 4, 'Should have Termux Local, GitHub, ZIP, and Cancel buttons');
assert.ok(buttons[0].data.custom_id.startsWith('botstudio_local_'), 'Button 1 must be Termux Local Workspace');
assert.ok(buttons[1].data.custom_id.startsWith('botstudio_gh_'), 'Button 2 must be GitHub push');
assert.ok(buttons[2].data.custom_id.startsWith('botstudio_zip_'), 'Button 3 must be ZIP download');
assert.ok(buttons[3].data.custom_id.startsWith('botstudio_cancel_'), 'Button 4 must be Cancel');
console.log('  ✅ Session and interactive choice payload verified!');

// 3. Test Full Multi-File Bot Scaffolding in Isolated Workspace
console.log('\n▶ Test 3: Multi-File Bot Scaffolding & Watermark Verification');
(async () => {
    const scaffoldRes = await botStudio.scaffoldCompleteBot('code a complex discord bot for me', { botName: 'astral-guardian-bot' });
    assert.ok(scaffoldRes.workspacePath, 'Workspace path must be defined');
    assert.ok(fs.existsSync(scaffoldRes.workspacePath), 'Workspace folder must exist');

    // Check key files
    const expectedFiles = [
        'package.json',
        '.env.example',
        'README.md',
        'deploy-commands.js',
        'ecosystem.config.js',
        'src/config.js',
        'src/index.js',
        'src/modules/starryLink.js',
        'src/commands/ping.js',
        'src/commands/help.js',
        'src/commands/botinfo.js',
        'src/commands/mod.js',
        'src/commands/economy.js',
        'src/commands/ticket.js',
        'src/commands/utility.js'
    ];

    for (const f of expectedFiles) {
        const fullP = path.join(scaffoldRes.workspacePath, f);
        assert.ok(fs.existsSync(fullP), `Expected file ${f} must exist in generated workspace`);
        
        // Check non-removable watermark on JS files
        if (f.endsWith('.js')) {
            const content = fs.readFileSync(fullP, 'utf8');
            assert.ok(content.includes('ARCHITECTURE GENERATED BY STARRY (ASTRAEA) BOT STUDIO'), `${f} must include Starry watermark`);
            assert.ok(content.includes('Non-Removable Core Attribution'), `${f} must enforce non-removable attribution`);
        }
    }

    // Verify Starry Link Telemetry Gateway integration
    const indexContent = fs.readFileSync(path.join(scaffoldRes.workspacePath, 'src/index.js'), 'utf8');
    assert.ok(indexContent.includes("require('./modules/starryLink')"), 'index.js must import starryLink');
    assert.ok(indexContent.includes('initStarryGateway(client)'), 'index.js must initialize Starry Gateway');

    console.log(`  ✅ Scaffolding verified! Created ${scaffoldRes.fileCount} files with Starry watermarks & telemetry link.`);

    // 4. Test Syntax Verification of All Generated JS Files
    console.log('\n▶ Test 4: Syntax Verification of Scaffolded Code');
    child_process.execSync(`node -c src/index.js && node -c src/modules/starryLink.js && node -c deploy-commands.js`, {
        cwd: scaffoldRes.workspacePath
    });
    console.log('  ✅ All generated JS files are 100% syntactically valid!');

    // 5. Test ZIP Archive Creation
    console.log('\n▶ Test 5: ZIP Archive Packaging');
    const zipRes = await botStudio.packageBotZip(scaffoldRes.workspacePath, scaffoldRes.botSlug);
    assert.ok(fs.existsSync(zipRes.zipPath), 'ZIP archive must exist on disk');
    const stat = fs.statSync(zipRes.zipPath);
    assert.ok(stat.size > 1000, 'ZIP archive must be non-empty (>1KB)');
    console.log(`  ✅ ZIP packaging verified! Created ${zipRes.zipFilename} (${stat.size} bytes).`);

    // Clean up test workspace
    try {
        fs.rmSync(scaffoldRes.workspacePath, { recursive: true, force: true });
        if (fs.existsSync(zipRes.zipPath)) fs.unlinkSync(zipRes.zipPath);
    } catch (e) {}

    console.log('\n✨ ALL STARRY BOT STUDIO TESTS PASSED WITH 100% SUCCESS RATE!\n');
    process.exit(0);
})().catch(err => {
    console.error('❌ Bot Studio Test Failed:', err);
    process.exit(1);
});
